### ISSUE TITLE
Advanced color picker issue

### ISSUE THREAD

**Issue by ghost** [blackwarthog/opentoonz#17]
Hi, 

I don't know why but i can't find the advanced color picker on windows panel. That was removed ? morevena 1.201 12.02 too.

**Comment by morevnaproject** [comment]
Hello Openanim! Please let me know what is your operating system?

**Comment by morevnaproject** [comment]
Please also check solution here - https://morevnaproject.org/2017/12/19/opentoonz-morevna-edition-version-1-2-0-1/#comment-1907980

**Comment by ghost** [comment]
Hey Konstantin, thanks  ! It's reapears after renaming the stuff folder. 👍
