### ISSUE TITLE
Mypaint Brushes are not being loaded

### ISSUE THREAD

**Issue by xfry** [blackwarthog/opentoonz#2]
When I open the OpenToonz Appimage (64 Bit) in **ubuntu 14.04 LTS** and then goes to **> Style Editor > Mypaint Brush**. It's shows empty without any Brush. Here you can see the image below.
![brushed](https://cloud.githubusercontent.com/assets/410885/24016739/518b0836-0a5b-11e7-8fb4-ed9b280108ab.png)
What can I do to solve this? Can you help me to load the brushes?

**Comment by jeneverito** [comment]
Almost the same thing happens to me in UBUNTU studio 14.04 32 bit. By the way,Thank you very much for this effort

**Comment by blackwarthog** [comment]
Thank you. I was sure that i've fixed it for appimage.

There is two possible problems

1. Wrong paths was set in `~/.config/OpenToonz/SystemVar.ini` while first start. To fix it for your computer you may replace value of two following variables in `~/.config/OpenToonz/SystemVar.ini` with:
```
TOONZFXPRESETS="/home/YOURUSERNAME/.config/OpenToonz/stuff/fxs"
TOONZLIBRARY="/home/YOURUSERNAME/.config/OpenToonz/stuff/library"
```
This fix also makes more vector brushes and textures avaiable in OpenToonz. (see PR #1090)

2. You already used OpenToonz before and stuff-folder was installed without brushes. You may install it by run appimage from terminal with the following command-line arguments:

```
./OpenToonz-1.1.2-mypaint-2017.03.16-linux-64bits.appimage \
    --appimage-exec cp -r "../share/opentoonz/stuff/library/mypaint brushes" \
    ~/".config/OpenToonz/stuff/library"
```

As alternative you may install MyPaint and solve two above problems. OpenToonz can load brushes directly from MyPaint if it presents in system.

**Comment by xfry** [comment]
@blackwarthog Thank you so much, the first point works, but the second one does not. Then I tried installing MyPaint and mypaint brushes works. Thank you so much, I make a donation to the project.

**Comment by jeneverito** [comment]
Thanks @blackwarthog ! It's work fine for me,

**Comment by blackwarthog** [comment]
I've updated appimage to solve the problem.
