### ISSUE TITLE
Why the colours...?

### ISSUE THREAD

**Issue by jeneverito** [blackwarthog/opentoonz#4]
Hello I'm testing OpenToonzMypaint appimage in Ubuntu 14.04 32 bit . It's Work fine but any color in any level  have an effect like "Multiply". It's a bug or I'm wrong?
![screenshot - 190317 - 16 39 18](https://cloud.githubusercontent.com/assets/26473031/24084205/84fbf0ca-0cc4-11e7-8c98-729a57d07e94.png)

(Sorry my bad english)

**Comment by blackwarthog** [comment]
I've fixed it now. I'll tell you when appimage will updated.

**Comment by jeneverito** [comment]
Thanks a lot!

**Comment by blackwarthog** [comment]
I've updated appimages. Fixed bug with blending also implemented smooth interpolation of strokes.

**Comment by jeneverito** [comment]
Thanks **blackwarthog**!
