### ISSUE TITLE
Display "Lock Alpha" in brush toolbar

### ISSUE THREAD

**Issue by 2dvision** [blackwarthog/opentoonz#5]
Thanks for MyPaint brushes. is it possible add "Lock Alpha" option to brush toolbar? This feature is in Krita:

![114698e851](https://cloud.githubusercontent.com/assets/16509592/24866316/4b2231fc-1df9-11e7-92e5-ef46c114b732.gif)

**Comment by blackwarthog** [comment]
You can set "lock alpha" option in style settings to 1. This value will saved in current style, and you will can switch to your lock-alpha brush just by selecting style (by mouse or numpad hotkeys).

**Comment by 2dvision** [comment]
I understand but my point was that, This shortcut is useful and easy way for this. For example Krita add this shortcut to toolbar (This feature exist in layer properties.) and i personally use this a lot. I do not know, Perhaps it not be necessary for all user.

**Comment by blackwarthog** [comment]
Separate style with configured lock-alpha can be used as a shortcut. May it be useful for you?

**Comment by blackwarthog** [comment]
I think i understand :) if you have a lot of brushes in active use, it's may be hard to create separate style for each.

What do you think about "eraser mode"? It's present in toolbar of MyPaint. Will it option helpful in toolbar?

**Comment by 2dvision** [comment]
> I think i understand :) if you have a lot of brushes in active use, it's may be hard to create separate style for each.

:+1:  :))

> What do you think about "eraser mode"? It's present in toolbar of MyPaint. Will it option helpful in toolbar?

Yes, I think It will be perfect.


You can find "Paint Mode: Lock Alpha" inside **Brush > Paint Mode** in MyPaint. This is what I mean:

![7439e73854](https://cloud.githubusercontent.com/assets/16509592/24892357/9d79b6c4-1e6b-11e7-954f-5a96bf1dbc5e.gif)

**Comment by 2dvision** [comment]
Is it possible add **Paint Mode** to toolbar like this?

![paint-mode](https://cloud.githubusercontent.com/assets/16509592/25065023/614de10a-21f6-11e7-8401-c5ce609032ca.png)

**Comment by blackwarthog** [comment]
implemented in latest (and some previous) releases
