### ISSUE TITLE
Display brush color in Level Palette

### ISSUE THREAD

**Issue by 2dvision** [blackwarthog/opentoonz#6]
![display color](https://cloud.githubusercontent.com/assets/16509592/24868265/0bf10a66-1dff-11e7-9c09-602a54e8f195.jpeg)

**Comment by blackwarthog** [comment]
Done! I've updated linux-appimages and windows installer. You already can download them.
Thanks for your respose.

**Comment by 2dvision** [comment]
awesome, Thanks!
